# -*- coding: utf-8 -*-
"""Molecular_Processing_Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lFVNqsVCKydbTNaZxLwnR4z4qFNissE
"""

from rdkit import Chem, DataStructs, rdBase
from rdkit.Chem import (Draw, PandasTools, AllChem, rdDepictor, rdMolDescriptors,
                        rdFMCS, rdmolops, Descriptors)
from rdkit.Chem.Draw import IPythonConsole, rdMolDraw2D
from molvs import standardize_smiles
import pandas as pd
from tqdm import tqdm
import io
from PIL import Image
import os
rdDepictor.SetPreferCoordGen(True)

sample_data = pd.read_csv('XiaoKongLongZuiKeAi.csv',encoding='utf_8_sig')

def standardise(smiles):
    std_smiles = standardize_smiles(smiles)
    return standardize_smiles (smiles)

sample_data['Standardise_SMILES'] = sample_data['SMILES'].apply(standardise)
idx = sample_data.columns.get_loc('SMILES') + 1
# Remove the column and reinsert it to the desired location
standard_smiles_col = sample_data.pop('Standardise_SMILES')
sample_data.insert(idx, 'Standardise_SMILES', standard_smiles_col)

smiles_list = sample_data['Standardise_SMILES']
mols = [Chem.MolFromSmiles(smi) for smi in smiles_list]

def _get_macrocycle_ring_mol(mol, strip=False):
    Chem.RemoveStereochemistry(mol)
    Chem.Kekulize(mol, clearAromaticFlags=True)
    ri = mol.GetRingInfo()
    atoms_ring = max(ri.AtomRings(), key=len)
    if strip:
        macrocycle_smiles = AllChem.MolFragmentToSmiles(mol, atomsToUse=list(atoms_ring))
    else:
        query = Chem.MolFromSmarts('[!#1;!#7]~[R]*')
        matches = mol.GetSubstructMatches(query)
        atoms_to_use = list(atoms_ring) + [m[0] for m in matches]
        macrocycle_smiles = AllChem.MolFragmentToSmiles(mol, atomsToUse=atoms_to_use)
    macrocycle_mol = Chem.MolFromSmiles(macrocycle_smiles)
    mol_frags = rdmolops.GetMolFrags(macrocycle_mol, asMols=True)
    largest_mol = max(mol_frags, default=macrocycle_mol, key=lambda m: m.GetNumAtoms())
    return largest_mol

class process:
    def __init__(self, list_of_smiles):
        self.smiles = list_of_smiles
        #self.standardized_smiles = [standardize_smiles(smi) for smi in list_of_smiles]
        self.mols = [Chem.MolFromSmiles(smi) for smi in self.smiles]

    def get_macrocycle_ring_size(self):
        ring_sizes = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=True)
            ring_size = macrocycle_mol.GetNumBonds()
            ring_sizes.append(ring_size)
        return ring_sizes

    def get_macrocycle_ring_size_for_mol (self,mol):
        macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=True)
        ring_size = macrocycle_mol.GetNumBonds()
        return ring_size

    def get_free_amide_count(self):
        free_amide_counts = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
            free_amide_smart = Chem.MolFromSmarts('[Nh][CX3]=[O]')
            free_amide_count = len(macrocycle_mol.GetSubstructMatches(free_amide_smart))
            free_amide_counts.append(free_amide_count)
        return free_amide_counts

    def get_free_amide_count_for_mol(self, mol):
        macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
        free_amide_smart = Chem.MolFromSmarts('[Nh][CX3]=[O]')
        return len(macrocycle_mol.GetSubstructMatches(free_amide_smart))

    def get_sub_amide_count(self):
        sub_amide_counts = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
            free_amide_count = self.get_free_amide_count_for_mol(mol)
            all_amide_smart = Chem.MolFromSmarts('[#6](=[#8])-[#7]-[#6]')
            all_amide_count = len(macrocycle_mol.GetSubstructMatches(all_amide_smart))
            sub_amide_count = (all_amide_count - free_amide_count) / 2
            sub_amide_counts.append(sub_amide_count)
        return sub_amide_counts

    def get_sub_amide_count_for_mol(self, mol):
        macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
        free_amide_count = self.get_free_amide_count_for_mol(mol)
        all_amide_smart = Chem.MolFromSmarts('[#6](=[#8])-[#7]-[#6]')
        all_amide_count = len(macrocycle_mol.GetSubstructMatches(all_amide_smart))
        sub_amide_count = (all_amide_count - free_amide_count) / 2
        return sub_amide_count

    def get_overall_amide_count(self):
        overall_amide_counts = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
            free_amide_count = self.get_free_amide_count_for_mol(mol)
            sub_amide_count = self.get_sub_amide_count_for_mol(mol)
            overall_amide_count = free_amide_count + sub_amide_count
            overall_amide_counts.append(overall_amide_count)
        return overall_amide_counts

    def get_macrocycle_core_smiles(self):
        core_smiles = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=True)
            macrocycle_core_smiles = Chem.MolToSmiles(macrocycle_mol)
            core_smiles.append(macrocycle_core_smiles)
        return core_smiles

    def get_macrocycle_peripheral_smiles(self):
        peripheral_smiles_list = []
        for mol in tqdm(self.mols):
            # 获取大环的原子
            ri = mol.GetRingInfo()
            atoms_ring = set(max(ri.AtomRings(), key=len))
            
            # 获取连接到大环的单重原子基团（包括可能通过多点连接的环状结构如环氧、环丙烷、氮杂环丙烷）
            peripheral_atoms = set()
            peripheral_groups = []
            
            # 找出所有直接连接到大环的原子
            for ring_atom_idx in atoms_ring:
                ring_atom = mol.GetAtomWithIdx(ring_atom_idx)
                for neighbor in ring_atom.GetNeighbors():
                    neighbor_idx = neighbor.GetIdx()
                    if neighbor_idx not in atoms_ring and neighbor.GetSymbol() != 'H':
                        # 检查是否是单原子基团或小环结构（如环氧、环丙烷、氮杂环丙烷）
                        if neighbor.IsInRing():  # 如果是环的一部分
                            # 获取包含这个原子的最小环
                            for ring in ri.AtomRings():
                                if neighbor_idx in ring:
                                    # 检查这个环是否足够小（例如3个原子的环）且与大环有多个连接点
                                    if len(ring) <= 3:  # 环氧、环丙烷或氮杂环丙烷大小
                                        # 检查这个小环是否有多个连接点连到大环
                                        connection_points = sum(1 for atom_idx in ring if any(
                                            neigh.GetIdx() in atoms_ring for neigh in mol.GetAtomWithIdx(atom_idx).GetNeighbors()))
                                        if connection_points >= 1:
                                            peripheral_atoms.update(ring)
                        else:  # 不是环的一部分，是单原子基团
                            peripheral_atoms.add(neighbor_idx)
            
            # 如果找到了外围基团，提取它们的SMILES
            if peripheral_atoms:
                atoms_to_use = list(peripheral_atoms.union(atoms_ring))
                try:
                    peripheral_smiles = AllChem.MolFragmentToSmiles(mol, atomsToUse=atoms_to_use)
                    peripheral_smiles_list.append(peripheral_smiles)
                except:
                    # 处理可能的错误情况
                    peripheral_smiles_list.append("")
            else:
                peripheral_smiles_list.append("")
                
        return peripheral_smiles_list

    def get_peripheral_groups_for_mol(self, mol):
        """
        为单个分子识别外围基团，返回包含每个外围基团SMILES的列表
        """
        # 获取大环的原子
        ri = mol.GetRingInfo()
        atoms_ring = set(max(ri.AtomRings(), key=len))
        
        # 存储识别到的所有外围基团
        peripheral_groups = []
        visited = set()
        
        # 找出所有直接连接到大环的原子
        for ring_atom_idx in atoms_ring:
            ring_atom = mol.GetAtomWithIdx(ring_atom_idx)
            for neighbor in ring_atom.GetNeighbors():
                neighbor_idx = neighbor.GetIdx()
                
                # 如果不是大环的一部分且不是氢原子
                if neighbor_idx not in atoms_ring and neighbor.GetSymbol() != 'H' and neighbor_idx not in visited:
                    # 检查是否是小环结构（如环氧、环丙烷、氮杂环丙烷）
                    if neighbor.IsInRing():
                        for ring in ri.AtomRings():
                            if neighbor_idx in ring and len(ring) <= 3:  # 小环（≤3个原子）
                                # 检查这个小环是否有连接点连到大环
                                connection_points = sum(1 for atom_idx in ring if any(
                                    neigh.GetIdx() in atoms_ring for neigh in mol.GetAtomWithIdx(atom_idx).GetNeighbors()))
                                if connection_points >= 1:
                                    # 提取这个小环作为一个外围基团
                                    group_atoms = list(ring)
                                    # 添加连接点
                                    for atom_idx in ring:
                                        atom = mol.GetAtomWithIdx(atom_idx)
                                        for neigh in atom.GetNeighbors():
                                            if neigh.GetIdx() in atoms_ring:
                                                group_atoms.append(neigh.GetIdx())
                                    
                                    try:
                                        group_smiles = AllChem.MolFragmentToSmiles(mol, atomsToUse=group_atoms)
                                        peripheral_groups.append(group_smiles)
                                        visited.update(ring)
                                    except:
                                        pass
                    else:
                        # 单原子基团 - 跟踪从这个原子开始的基团
                        group_atoms = self._trace_group_from_atom(mol, neighbor_idx, atoms_ring)
                        if len(group_atoms) > 0:
                            try:
                                group_smiles = AllChem.MolFragmentToSmiles(mol, atomsToUse=group_atoms)
                                peripheral_groups.append(group_smiles)
                                visited.update(group_atoms)
                            except:
                                pass
        
        return peripheral_groups
    
    def _trace_group_from_atom(self, mol, start_atom_idx, ring_atoms, max_depth=1):
        """
        从起始原子追踪一个基团，限制为单个重原子（非氢）
        ring_atoms: 大环原子的集合
        max_depth: 追踪的最大深度（限制为1表示只包含直接连接的单个重原子）
        """
        group_atoms = [start_atom_idx]
        
        # 添加与大环的连接点
        start_atom = mol.GetAtomWithIdx(start_atom_idx)
        for neigh in start_atom.GetNeighbors():
            if neigh.GetIdx() in ring_atoms:
                group_atoms.append(neigh.GetIdx())
        
        return group_atoms

    def get_macrocycle_free_amide_ratio (self):
        macrocycle_free_amide_ratios = []
        for mol in tqdm(self.mols):
            free_amide_count = self.get_free_amide_count_for_mol(mol)
            ring_size = self.get_macrocycle_ring_size_for_mol(mol)
            free_amide_ratio = free_amide_count*3/ring_size
            macrocycle_free_amide_ratios.append(free_amide_ratio)
        return macrocycle_free_amide_ratios

    def get_macrocycle_amide_ratio (self):
        macrocycle_amide_ratios = []
        for mol in tqdm(self.mols):
            macrocycle_mol = _get_macrocycle_ring_mol(mol, strip=False)
            free_amide_count = self.get_free_amide_count_for_mol(mol)
            sub_amide_count = self.get_sub_amide_count_for_mol(mol)
            overall_amide_count = free_amide_count + sub_amide_count
            ring_size = self.get_macrocycle_ring_size_for_mol(mol)
            amide_ratio = overall_amide_count*3/ring_size
            macrocycle_amide_ratios.append(amide_ratio)
        return macrocycle_amide_ratios

    def get_num_of_rings (self):
        num_rings = []
        for mol in tqdm(self.mols):
            num_ring = mol.GetRingInfo().NumRings()
            num_rings.append(num_ring)
        return num_rings

    def get_num_of_aromatic_rings(self):
        aromatic_rings = []
        for mol in tqdm(self.mols):
            aromatic_rings = [ring for ring in mol.GetRingInfo().AtomRings() if all(mol.GetAtomWithIdx(idx).GetIsAromatic() for idx in ring)]
            num_aromatic_rings = len(aromatic_rings)
            aromatic_rings.append(num_aromatic_rings)
        return len(aromatic_rings)

    def get_cLogP(self):
        cLogP = []
        for mol in tqdm(self.mols):
            cLogP.append(Descriptors.MolLogP(mol))
        return cLogP

    def get_molecular_weight(self):
        molecular_weights = []
        for mol in tqdm(self.mols):
            molecular_weight = Descriptors.MolWt(mol)
            molecular_weights.append(molecular_weight)
        return molecular_weights

    def get_Num_H_Acceptors(self):
        Num_H_Acceptors = []
        for mol in tqdm(self.mols):
            Num_H_Acceptor = Descriptors.NumHAcceptors(mol)
            Num_H_Acceptors.append(Num_H_Acceptor)
        return Num_H_Acceptors

    def get_Num_H_donors(self):
        Num_H_donors = []
        for mol in tqdm(self.mols):
            Num_H_donor = Descriptors.NumHDonors(mol)
            Num_H_donors.append(Num_H_donor)
        return Num_H_donors

    def get_Num_Heavy_Atoms(self):
        Num_Heavy_Atoms = []
        for mol in tqdm(self.mols):
            Num_Heavy_Atom = Descriptors.HeavyAtomCount(mol)
            Num_Heavy_Atoms.append(Num_Heavy_Atom)
        return Num_Heavy_Atoms

    def get_Num_Carbon_Atoms(self):
        Num_Carbon_Atoms = []
        for mol in tqdm(self.mols):
            Num_Carbon_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'C')
            Num_Carbon_Atoms.append(Num_Carbon_Atom)
        return Num_Carbon_Atoms

    def get_Num_Nitrogen_Atoms(self):
        Num_Nitrogen_Atoms = []
        for mol in tqdm(self.mols):
            Num_Nitrogen_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'N')
            Num_Nitrogen_Atoms.append(Num_Nitrogen_Atom)
        return Num_Nitrogen_Atoms

    def get_Num_Oxygen_Atoms(self):
        Num_Oxygen_Atoms = []
        for mol in tqdm(self.mols):
            Num_Oxygen_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'O')
            Num_Oxygen_Atoms.append(Num_Oxygen_Atom)
        return Num_Oxygen_Atoms

    def get_Num_Sulfur_Atoms(self):
        Num_Sulfur_Atoms = []
        for mol in tqdm(self.mols):
            Num_Sulfur_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'S')
            Num_Sulfur_Atoms.append(Num_Sulfur_Atom)
        return Num_Sulfur_Atoms

    def get_Num_Phosphorus_Atoms(self):
        Num_Phosphorus_Atoms = []
        for mol in tqdm(self.mols):
            Num_Phosphorus_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'P')
            Num_Phosphorus_Atoms.append(Num_Phosphorus_Atom)
        return Num_Phosphorus_Atoms

    def get_fraction_sp3_carbons(self):
        fraction_sp3_carbons = []
        sp3_carbons = 0
        total_carbons = 0
        for mol in tqdm(self.mols):
            for atom in mol.GetAtoms():
              if atom.GetSymbol() == 'C':  # Check if the atom is a carbon atom
                total_carbons += 1
              if atom.GetHybridization() == Chem.HybridizationType.SP3:
                sp3_carbons += 1
            if total_carbons == 0:
              fraction_sp3_carbon = 0
            else:
              fraction_sp3_carbon = sp3_carbons / total_carbons

            fraction_sp3_carbons.append(fraction_sp3_carbon)
        return fraction_sp3_carbons

    def get_TPSA(self):
        TPSA = []
        for mol in tqdm(self.mols):
            tpsa = Descriptors.TPSA(mol)
            TPSA.append(tpsa)
        return TPSA
    
    def get_TPSA_with_S_and_P(self):
        TPSA_with_S_and_P = []
        for mol in tqdm(self.mols):
            tpsa_with_S_and_P_num = Descriptors.TPSA(mol, includeSandP=True)
            TPSA_with_S_and_P.append(tpsa_with_S_and_P_num)
        return TPSA_with_S_and_P

    def get_Num_Rotatable_Bonds(self):
        Num_Rotatable_Bonds = []
        for mol in tqdm(self.mols):
            Num_Rotatable_Bond = Descriptors.NumRotatableBonds(mol)
            Num_Rotatable_Bonds.append(Num_Rotatable_Bond)

        return Num_Rotatable_Bonds

    def get_Num_Charged_Atoms(self):
        Num_Charged_Atoms = []
        for mol in tqdm(self.mols):
            Num_Charged_Atom = sum(1 for atom in mol.GetAtoms() if atom.GetFormalCharge() != 0)
            Num_Charged_Atoms.append(Num_Charged_Atom)
        return Num_Charged_Atoms
    
    def get_Net_Charge(self):
        Net_Charge = []
        for mol in tqdm(self.mols):
            net_charge = rdmolops.GetFormalCharge(mol)
            Net_Charge.append(net_charge)
        return Net_Charge

    def get_Kier_index(self):
        Kier_index = []
        for mol in tqdm(self.mols):
            kier_index = Descriptors.Kappa1(mol)*Descriptors.Kappa2(mol)/Descriptors.HeavyAtomCount(mol)
            Kier_index.append(kier_index)
        return Kier_index

    def get_InchiKey (self):
        InchiKey = []
        for mol in tqdm(self.mols):
            inchi_key = Chem.inchi.MolToInchiKey(mol)
            InchiKey.append(inchi_key)
        return InchiKey


    def result(self):
        Macrocycle_Ring_Sizes = self.get_macrocycle_ring_size()
        Macrocycle_Free_Amide_Counts = self.get_free_amide_count()
        Macrocycle_Substituted_Amide_Count = self.get_sub_amide_count()
        Macrocycle_Overall_Amide_Count = self.get_overall_amide_count()
        Macrocycle_Core_Smiles = self.get_macrocycle_core_smiles()
        Macrocycle_Peripheral_Smiles = self.get_macrocycle_peripheral_smiles()
        Macrocycle_free_amide_ratios = self.get_macrocycle_free_amide_ratio()
        Macrocycle_amide_ratios = self.get_macrocycle_amide_ratio()
        Num_Rings = self.get_num_of_rings()
        Num_Aromatic_Rings = self.get_num_of_aromatic_rings()
        cLogP = self.get_cLogP()
        Molecular_Weight = self.get_molecular_weight()
        Num_H_Acceptors = self.get_Num_H_Acceptors()
        Num_H_donors = self.get_Num_H_donors()
        Num_Heavy_Atoms = self.get_Num_Heavy_Atoms()
        Num_Carbon_Atoms = self.get_Num_Carbon_Atoms()
        Num_Nitrogen_Atoms = self.get_Num_Nitrogen_Atoms()
        Num_Oxygen_Atoms = self.get_Num_Oxygen_Atoms()
        Num_Sulfur_Atoms = self.get_Num_Sulfur_Atoms()
        Num_Phosphorus_Atoms = self.get_Num_Phosphorus_Atoms()
        fraction_sp3_carbons = self.get_fraction_sp3_carbons()
        TPSA = self.get_TPSA()
        TPSA_with_S_and_P = self.get_TPSA_with_S_and_P()
        Num_Rotatable_Bonds = self.get_Num_Rotatable_Bonds()
        Num_Charged_Atoms = self.get_Num_Charged_Atoms()
        Net_Charge = self.get_Net_Charge()
        Kier_index = self.get_Kier_index()
        InchiKey = self.get_InchiKey()



        result_df = pd.DataFrame({
            "Macrocycle_Ring_Size": Macrocycle_Ring_Sizes,
            "Macrocycle_Free_Amide_Count": Macrocycle_Free_Amide_Counts,
            "Macrocycle_Substituted_Amide_Count": Macrocycle_Substituted_Amide_Count,
            "Macrocycle_Overall_Amide_Count": Macrocycle_Overall_Amide_Count,
            "Macrocycle_Core_Smiles": Macrocycle_Core_Smiles,
            "Macrocycle_Peripheral_Smiles": Macrocycle_Peripheral_Smiles,
            "Macrocycle_free_amide_ratios":Macrocycle_free_amide_ratios,
            "Macrocycle_amide_ratios":Macrocycle_amide_ratios,
            "Num_Rings":Num_Rings,
            "Num_Aromatic_Rings":Num_Aromatic_Rings,
            "cLogP":cLogP,
            "Molecular_Weight":Molecular_Weight,
            "Num_H_Acceptors":Num_H_Acceptors,
            "Num_H_donors":Num_H_donors,
            "Num_Heavy_Atoms":Num_Heavy_Atoms,
            "Num_Carbon_Atoms":Num_Carbon_Atoms,
            "Num_Nitrogen_Atoms": Num_Nitrogen_Atoms,
            "Num_Oxygen_Atoms": Num_Oxygen_Atoms,
            "Num_Sulfur_Atoms": Num_Sulfur_Atoms,
            "Num_Phosphorus_Atoms": Num_Phosphorus_Atoms,
            "Fraction_SP3_Carbons":fraction_sp3_carbons,
            "TPSA":TPSA,
            "TPSA(withSandP)":TPSA_with_S_and_P,
            "Num_Rotatable_Bonds":Num_Rotatable_Bonds,
            "Num_Charged_Atoms":Num_Charged_Atoms,
            "Net_Charge":Net_Charge,
            "Kier_index":Kier_index,
            "InchiKey":InchiKey})
        return result_df

rdkit_featurizer = process(smiles_list)
rdkit_features = rdkit_featurizer.result()
result_df = pd.concat([sample_data, rdkit_features], axis =1)
result_df.to_csv("XiaoKongLongZuiKeAi-Result.csv",encoding='utf_8_sig')

## Define directory names using os.path.expanduser to get the proper user desktop path
#desktop_path = os.path.expanduser("~/Desktop")
#dir_name = os.path.join(desktop_path, "Overall_images")
#dir_name_2 = os.path.join(desktop_path, "Overall_sdf")
#
#def create_directory(path):
#    """Safely create directory if it doesn't exist"""
#    try:
#        if not os.path.exists(path):
#            os.makedirs(path)
#        return True
#    except OSError as e:
#        print(f"Error creating directory {path}: {e}")
#        return False
#
#def process_molecules(sample_data):
#    """Process molecules and create images and SDF files"""
#    # Drop duplicates
#    sample_data = sample_data.drop_duplicates(subset='Standardise_SMILES', keep="first")
#    
#    # Create directories
#    if not all(create_directory(d) for d in [dir_name, dir_name_2]):
#        print("Failed to create one or more directories. Exiting.")
#        return
#
#    # Process molecules
#    for index, row in sample_data.iterrows():
#        molecule = row['Standardise_SMILES']
#        mol_id = row['ID']
#        
#        if not molecule:
#            print(f"Empty SMILES string at index {index}")
#            continue
#
#        try:
#            mol = Chem.MolFromSmiles(molecule)
#            if mol is None:
#                print(f"Failed to parse SMILES at index {index}: {molecule}")
#                continue
#
#            # Create and save PNG
#            try:
#                drawer = rdMolDraw2D.MolDraw2DCairo(600, 600)
#                drawer.drawOptions().clearBackground = False
#                drawer.drawOptions().addStereoAnnotation = False
#                drawer.DrawMolecule(mol)
#                drawer.FinishDrawing()
#                img_data = drawer.GetDrawingText()
#                
#                png_path = os.path.join(dir_name, f"{mol_id}.png")
#                with open(png_path, 'wb') as f:
#                    f.write(img_data)
#            except Exception as e:
#                print(f"Error creating PNG for molecule {mol_id}: {e}")
#
#            # Create and save SDF
#            try:
#                sdf_path = os.path.join(dir_name_2, f"{mol_id}.sdf")
#                Chem.MolToMolFile(mol, sdf_path)
#            except Exception as e:
#                print(f"Error creating SDF for molecule {mol_id}: {e}")
#
#        except Exception as e:
#            print(f"Error processing molecule at index {index}: {e}")
#
## Usage
#if __name__ == "__main__":
#    # Assuming sample_data is your pandas DataFrame
#    try:
#        process_molecules(sample_data)
#        print("Processing completed successfully")
#    except Exception as e:
#        print(f"An error occurred during processing: {e}")